package com.example.peopledaliy.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.peopledaliy.mvp.model.entity.UserEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_ENTITY".
*/
public class UserEntityDao extends AbstractDao<UserEntity, Long> {

    public static final String TABLENAME = "USER_ENTITY";

    /**
     * Properties of entity UserEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property User_id = new Property(1, int.class, "user_id", false, "USER_ID");
        public final static Property User_phone = new Property(2, int.class, "user_phone", false, "USER_PHONE");
        public final static Property User_pwd = new Property(3, String.class, "user_pwd", false, "USER_PWD");
        public final static Property User_name = new Property(4, String.class, "user_name", false, "USER_NAME");
        public final static Property User_sex = new Property(5, String.class, "user_sex", false, "USER_SEX");
        public final static Property User_img = new Property(6, String.class, "user_img", false, "USER_IMG");
        public final static Property User_integral = new Property(7, int.class, "user_integral", false, "USER_INTEGRAL");
    }


    public UserEntityDao(DaoConfig config) {
        super(config);
    }
    
    public UserEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: user_id
                "\"USER_PHONE\" INTEGER NOT NULL ," + // 2: user_phone
                "\"USER_PWD\" TEXT," + // 3: user_pwd
                "\"USER_NAME\" TEXT," + // 4: user_name
                "\"USER_SEX\" TEXT," + // 5: user_sex
                "\"USER_IMG\" TEXT," + // 6: user_img
                "\"USER_INTEGRAL\" INTEGER NOT NULL );"); // 7: user_integral
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUser_id());
        stmt.bindLong(3, entity.getUser_phone());
 
        String user_pwd = entity.getUser_pwd();
        if (user_pwd != null) {
            stmt.bindString(4, user_pwd);
        }
 
        String user_name = entity.getUser_name();
        if (user_name != null) {
            stmt.bindString(5, user_name);
        }
 
        String user_sex = entity.getUser_sex();
        if (user_sex != null) {
            stmt.bindString(6, user_sex);
        }
 
        String user_img = entity.getUser_img();
        if (user_img != null) {
            stmt.bindString(7, user_img);
        }
        stmt.bindLong(8, entity.getUser_integral());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUser_id());
        stmt.bindLong(3, entity.getUser_phone());
 
        String user_pwd = entity.getUser_pwd();
        if (user_pwd != null) {
            stmt.bindString(4, user_pwd);
        }
 
        String user_name = entity.getUser_name();
        if (user_name != null) {
            stmt.bindString(5, user_name);
        }
 
        String user_sex = entity.getUser_sex();
        if (user_sex != null) {
            stmt.bindString(6, user_sex);
        }
 
        String user_img = entity.getUser_img();
        if (user_img != null) {
            stmt.bindString(7, user_img);
        }
        stmt.bindLong(8, entity.getUser_integral());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public UserEntity readEntity(Cursor cursor, int offset) {
        UserEntity entity = new UserEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // user_id
            cursor.getInt(offset + 2), // user_phone
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // user_pwd
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // user_name
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // user_sex
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // user_img
            cursor.getInt(offset + 7) // user_integral
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUser_id(cursor.getInt(offset + 1));
        entity.setUser_phone(cursor.getInt(offset + 2));
        entity.setUser_pwd(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setUser_name(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUser_sex(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setUser_img(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setUser_integral(cursor.getInt(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(UserEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(UserEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UserEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
